version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ahfai
      POSTGRES_USER: ahfai
      POSTGRES_PASSWORD: ahfai_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ahfai"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://ahfai:ahfai_password@postgres:5432/ahfai
      OLLAMA_HOST: http://ollama:11434
      SECRET_KEY: ${SECRET_KEY:-change-this-in-production}
      ALLOWED_ORIGINS: http://localhost:3000,http://frontend:3000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
