name: PRODUCTION_1 CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'PRODUCTION/PRODUCTION_1/**'
      - '.github/workflows/production-1-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'PRODUCTION/PRODUCTION_1/**'
      - '.github/workflows/production-1-ci.yml'

jobs:
  test:
    name: Test PRODUCTION_1
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: PRODUCTION/PRODUCTION_1
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: PRODUCTION/PRODUCTION_1/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint || true
      
      - name: Run type check
        run: npm run check || true
      
      - name: Run tests
        run: npm test
      
      - name: Build application
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-1-build
          path: PRODUCTION/PRODUCTION_1/build
          retention-days: 7

  docker:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        working-directory: PRODUCTION/PRODUCTION_1
        run: docker-compose build
      
      - name: Test Docker containers
        working-directory: PRODUCTION/PRODUCTION_1
        run: |
          docker-compose up -d
          sleep 10
          docker-compose ps
          docker-compose down

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: PRODUCTION/PRODUCTION_1
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run security audit
        run: npm audit --audit-level=moderate || true
      
      - name: Check for vulnerabilities
        run: npm audit --production || true

